export const campaigns = [
  {
    id: "c1",
    name: "Summer launch",
    objective: "Conversions",
    status: "active",
    budget: 120,
    platform: "Facebook",
    startDate: "2026-07-10",
    endDate: "2026-07-31",
  },
  {
    id: "c2",
    name: "Brand awareness",
    objective: "Awareness",
    status: "paused",
    budget: 200,
    platform: "TikTok",
    startDate: "2026-07-01",
    endDate: "2026-08-01",
  },
  {
    id: "c3",
    name: "App install push",
    objective: "App Installs",
    status: "active",
    budget: 85,
    platform: "Facebook",
    startDate: "2026-07-05",
    endDate: "2026-07-20",
  },
  {
    id: "c4",
    name: "Lead gen test",
    objective: "Lead Generation",
    status: "draft",
    budget: 60,
    platform: "TikTok",
    startDate: "2026-07-15",
    endDate: "2026-07-30",
  },
  {
    id: "c5",
    name: "Retargeting - cart",
    objective: "Conversions",
    status: "active",
    budget: 150,
    platform: "TikTok",
    startDate: "2026-07-02",
    endDate: "2026-07-29",
  },
  {
    id: "c6",
    name: "New collection",
    objective: "Traffic",
    status: "active",
    budget: 95,
    platform: "Facebook",
    startDate: "2026-07-12",
    endDate: "2026-08-05",
  },
];

export const ads = [
  {
    id: "a1",
    name: "Hero image - hero offer",
    adType: "Image",
    status: "active",
    body: "A strong offer-led image creative focused on fast checkout and seasonal pricing.",
    platforms: ["Facebook"],
  },
  {
    id: "a2",
    name: "Product teaser video",
    adType: "Video",
    status: "active",
    body: "Short video showing product use cases for faster trust and higher click-through rates.",
    platforms: ["TikTok", "Facebook"],
  },
  {
    id: "a3",
    name: "Story retargeting",
    adType: "Story",
    status: "paused",
    body: "Story-form ad targeted at recent site visitors with a limited-time discount.",
    platforms: ["Facebook"],
  },
  {
    id: "a4",
    name: "Carousel collection",
    adType: "Carousel",
    status: "active",
    body: "Multi-card product carousel for showcasing top SKUs directly in-feed.",
    platforms: ["TikTok", "Facebook"],
  },
  {
    id: "a5",
    name: "App install promo",
    adType: "Video",
    status: "draft",
    body: "App install promo highlighting onboarding speed and rewards.",
    platforms: ["TikTok"],
  },
  {
    id: "a6",
    name: "Lookalike static",
    adType: "Image",
    status: "active",
    body: "Static creative built for lookalike audiences with primary value proposition first.",
    platforms: ["Facebook"],
  },
];

export const integrations = [
  {
    id: "facebook",
    name: "Facebook Ads",
    status: "connected",
    accountName: "Acme Ad Account",
    lastSync: "2026-07-09",
  },
  {
    id: "tiktok",
    name: "TikTok Ads",
    status: "connected",
    accountName: "Acme TikTok Business",
    lastSync: "2026-07-09",
  },
];

export const settings = {
  workspaceName: "Acme Ads",
  defaultBrand: "Acme",
  defaultCurrency: "USD",
  timezone: "UTC",
};
